### ISSUE TITLE
Can't Scrape Azure Queues

### ISSUE THREAD

**Issue by NoamVH** [webdevops/azure-metrics-exporter#106]
Hello,

I've been trying to scrape Azure Queues in my environment.

I tried going after the examples in the ReadMe and after some examples in an [old issue](https://github.com/webdevops/azure-metrics-exporter/issues/9#issuecomment-851533537).

This is my configuration:

```
  - job_name: azure-metrics-queues
    scrape_interval: 1m
    metrics_path: /probe/metrics/list
    params:
      name: ["azure-metrics-queues"]
      subscription:
      - ********-****-****-****-************
      metricNamespace: ["Microsoft.Storage/storageAccounts/queueServices"]
      resourceSubPath:
      - queueServices/default
      filter:
      - resourceType eq 'Microsoft.Storage/storageAccounts'
      metric:
      - QueueCapacity
      - QueueCount
      - QueueMessageCount
      interval: ["PT1M"]
      timespan: ["PT1M"]
      aggregation:
      - Average
      - Total
    static_configs:
    - targets: ["azure-metrics-exporter:8080"]
```

I'm not seeing any problematic logs in either the Prometheus Server or Azure Metrics Exporter pods, what am I missing?

Another question - how do I set scraping for specific queues or storage accounts?

**Comment by NoamVH** [comment]
Update,

I managed to scrape queues by using the `resource` metrics path for the specific storage account, not as useful as a list, since this requires setting many targets instead of having the exporter find everything, but it's bearable to work with.

Another problem was that I scraped in interval and time span of PT1M, the main metric I wanted to get was messages count in different queues, and Azure scrapes queues message count [only once an hour](https://learn.microsoft.com/en-us/azure/storage/queues/monitor-queue-storage-reference#supported-metrics-for-microsoftstoragestorageaccountsqueueservicesl), trying to scrape for smaller intervals causes the API request to fail. Also, Azure doesn't allow splitting this metrics according to queues, but only shows a sum of all of the queues in a storage account, so I figured I'd use Ingress and Egress as metrics for my needs.

However, Azure doesn't allow splitting the Ingress and Egress metrics in a meaningful way either, only by API request name, Authentication type, and Geo type, making all of the metrics for Azure queues meaningless.

In any case, here's my scrape job definition snippet, it may still be useful if there's one queue in a storage account, or that the granularity of single queues in a storage account doesn't matter in someone's usecase:

```
- job_name: azure-metrics-queues
 scrape_interval: 1m
 metrics_path: /probe/metrics/resource
 params:
   name: ["azure-metrics-queues"]
   subscription:
   - ********-****-****-****-************
   target:
   - .../providers/Microsoft.Storage/storageAccounts/.../queueServices/default
   metric:
   - Egress
   - Ingress
   interval: ["PT1M"]
   timespan: ["PT1M"]
   aggregation:
   - average
 static_configs:
 - targets: ["azure-metrics-exporter:8080"]
```
