### ISSUE TITLE
segmentation violation

### ISSUE THREAD

**Issue by abelal83** [webdevops/azure-metrics-exporter#12]
First of all I would like to say thanks to you all for such an amazing exporter for Azure, compared to the others this is by far the best.

We've been using this exporter for a while inside Kubernetes, we noticed every so often container would crash with this error message

```
{"file":"main.go:58","func":"main","level":"info","msg":"starting azure-metrics-exporter v21.8.1 (cee9d9e; go1.16.6; by webdevops.io)"}
{"file":"main.go:59","func":"main","level":"info","msg":"{\"Logger\":{\"Debug\":false,\"Verbose\":false,\"LogJson\":true},\"Azure\":{\"Environment\":\"AZUREPUBLICCLOUD\",\"AdResourceUrl\":null,\"ServiceDiscovery\":{\"CacheDuration\":1800000000000}},\"Metrics\":{\"ResourceIdLowercase\":false,\"Template\":\"{name}\"},\"Prober\":{\"ConcurrencySubscription\":5,\"ConcurrencySubscriptionResource\":10,\"Cache\":false},\"ServerBind\":\":8080\"}"}
{"file":"main.go:63","func":"main","level":"info","msg":"init Azure connection"}
{"file":"main.go:67","func":"main","level":"info","msg":"starting http server on :8080"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x8f85c2]

goroutine 65503 [running]:
github.com/webdevops/azure-metrics-exporter/metrics.(*MetricProber).FetchMetricsFromTarget(0xc000076000, 0xc000160000, 0xc0002f2100, 0x7c, 0xc0001ac9c0, 0x4, 0x4, 0xc00048c240, 0x2, 0x2, ...)
	/go/src/github.com/webdevops/azure-metrics-exporter/metrics/insights.go:57 +0x462
github.com/webdevops/azure-metrics-exporter/metrics.(*MetricProber).collectMetricsFromTargets.func1.1.1(0xc00043f820, 0xc000076000, 0xc000160000, 0xc00027f440, 0xc0002f2100, 0x7c, 0xc0001ac9c0, 0x4, 0x4, 0xc00048c240, ...)
	/go/src/github.com/webdevops/azure-metrics-exporter/metrics/prober.go:186 +0xb8
created by github.com/webdevops/azure-metrics-exporter/metrics.(*MetricProber).collectMetricsFromTargets.func1.1
	/go/src/github.com/webdevops/azure-metrics-exporter/metrics/prober.go:184 +0x23e
```

There's only 2 scrape jobs configured in prometheus

```yaml
        - job_name: azure-metrics-redis
          scrape_interval: 1m
          metrics_path: /probe/metrics/list
          params:
            name: ["azure_redis"]
            subscription:
            - xxxxxxxxxxxxxxxxxxxx
            resourceType: ["Microsoft.Cache/Redis"]
            metric:
            - connectedclients
            - totalcommandsprocessed
            - cachehits
            - cachemisses
            - getcommands
            - setcommands
            - operationsPerSecond
            - evictedkeys
            - totalkeys
            - expiredkeys
            - usedmemory
            - usedmemorypercentage
            - usedmemoryRss
            - serverLoad
            - cacheWrite
            - cacheRead
            - percentProcessorTime
            - cacheLatency
            - errors
            interval: ["PT1M"]
            timespan: ["PT1M"]
            aggregation:
            - average
            - total
          static_configs:
          - targets: ["azure-metrics-exporter.azure-metrics:80"]

        - job_name: azure-metrics-appserviceplans
          scrape_interval: 1m
          metrics_path: /probe/metrics/list
          params:
            name: ["azure_appserviceplans"]
            subscription:
            - xxxxxxxxxxxxxxxxxxxxxx
            resourceType: ["Microsoft.Web/serverFarms"]
            metric:
            - BytesReceived
            - BytesSent
            - CpuPercentage
            - MemoryPercentage
            interval: ["PT1M"]
            timespan: ["PT5M"]
            aggregation:
            - average
            - total
            metricFilter: ["Instance eq '*'"]
            metricTop: ["10"]
          static_configs:
          - targets: ["azure-metrics-exporter.azure-metrics:80"]
```

Tried with just the redis scrape job which also causes the same crash. Are we doing anything wrong? In 43 hours we've had this error 20 times so far.
