### ISSUE TITLE
support filtering on kind/sku or any other returned value

### ISSUE THREAD

**Issue by abelal83** [webdevops/azure-metrics-exporter#13]
I have this job defined

```yaml
        - job_name: azure-metrics-sqldatabase
          scrape_interval: 1m
          metrics_path: /probe/metrics/list
          params:
            name: ["azure_sqldatabase"]
            subscription:
            - xxxx
            resourceType: ["Microsoft.Sql/servers/databases"]
            metric:
            - dtu_consumption_percent
            - storage_percent
            interval: ["PT5M"]
            timespan: ["PT5M"]
            aggregation:
            - average
            - maximum
          static_configs:
          - targets: ["azure-metrics-exporter.azure-metrics:80"]
```

This works however, we also get lots of warning such as 

{"file":"prober.go:189","func":"1","level":"warning","msg":"insights.MetricsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"BadRequest\" Message=\"Failed to find metric configuration for provider: Microsoft.Sql, resource Type: servers/databases, metric: dtu_consumption_percent, Valid metrics: cpu_percent,physical_data_read_percent,connection_successful,connection_failed,blocked_by_firewall,dwu_limit,dwu_consumption_percent,dwu_used,cache_hit_percent,cache_used_percent,local_tempdb_usage_percent,memory_usage_percent,wlg_allocation_relative_to_system_percent,wlg_allocation_relative_to_wlg_effective_cap_percent,wlg_active_queries,wlg_queued_queries,active_queries,queued_queries,wlg_active_queries_timeouts,wlg_effective_min_resource_percent,wlg_effective_cap_resource_percent\"","paramAggregation":["average","maximum"],"paramInterval":["PT5M"],"paramMetric":["dtu_consumption_percent","storage_percent"],"paramName":["azure_sqldatabase"],"paramResourceType":["Microsoft.Sql/servers/databases"],"paramSubscription":["xxxxxxxxxxx"],"paramTimespan":["PT5M"],"requestPath":"/probe/metrics/list","resourceID":"/subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Sql/servers/xxx-xx-xxx-xx/databases/xxx

The reason for this is dtu_consumption_percent is not valid for vCore databases. I checked filtering options https://docs.microsoft.com/en-us/rest/api/resources/resources/list but none can filter on `kind` which appears to determine type of SQL DB in use.

"kind": "v12.0,user" <- dtu based
 "kind": "v12.0,user,vcore" <- vCore

Is there a way to apply that sort filter within metrics exporter? I assume this may affect other Azure resources too where resource types depending on SKU or kind offer different types of metrics.

A suggestion would be an additional filter such as `resourceFilter` where filtering is done by metrics exporter once it has the list from Azure API?
```yaml
        - job_name: azure-metrics-sqldatabase
          scrape_interval: 1m
          metrics_path: /probe/metrics/list
          params:
            name: ["azure_sqldatabase"]
            subscription:
            - a75c7008-66c1-4373-a0f3-859abaefccdb
            resourceType: ["Microsoft.Sql/servers/databases"]
            resourceFilter: ["kind eq 'v12.0,user'"]
            metric:
            - dtu_consumption_percent
            - storage_percent
            interval: ["PT5M"]
            timespan: ["PT5M"]
            aggregation:
            - average
            - maximum
          static_configs:
          - targets: ["azure-metrics-exporter.azure-metrics:80"]
```

**Comment by mblaschke** [comment]
`resourceType` ist only a convenient config option which generating `resourceFilter`

it is just passed to the Azure resource API. you can have multiple clauses here and combine them with an `and`:
https://docs.microsoft.com/de-de/rest/api/resources/resources/list

try:
```
resourceFilter: ["resourceType eq 'Microsoft.Sql/servers/databases' and kind eq 'v12.0,user'"]
```

**Comment by abelal83** [comment]
unfortunately that API has limited support

Filter comparison operators include eq (equals) and ne (not equals) and may be used with the following properties: location, resourceType, name, resourceGroup, identity, identity/principalId, plan, plan/publisher, plan/product, plan/name, plan/version, and plan/promotionCode.

Therefore, in order to filter it has to be done after response.

**Comment by mblaschke** [comment]
Hm.. what about implementing Azure ResourceGraph API for servicediscovery? there we would have more possibilities for filtering

**Comment by abelal83** [comment]
That would most certainly help with fine grained filtering. For example https://docs.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph(2021-03-01)/resources/resources#filter-resources

**Comment by mblaschke** [comment]
next `webdevops/azure-metrics-exporter:main` includes ResourceGraph as servicediscovery with custom filtering (as part of the query)

had that already implemented in azure-resourcegraph-exporter so it wasn't that much work :)

**Comment by abelal83** [comment]
@mblaschke just wondering if you've had time to apply changes for graph api? Really keen to use it!

**Comment by mblaschke** [comment]
It's in the `main` branch since my last comment (7 days) and also published to docker hub/quay as `webdevops/azure-metrics-exporter:main`

Try it with: https://github.com/webdevops/azure-metrics-exporter#probemetricsresourcegraph-parameters

**Comment by abelal83** [comment]
thanks @mblaschke , wasn't sure if a docker image was available or not from main. I will give it a try today. Thanks again!

**Comment by abelal83** [comment]
@mblaschke just tried with this prometheus config

```yaml
        - job_name: azure-metrics-sqldatabase
          scrape_interval: 1m
          #metrics_path: /probe/metrics/list
          metrics_path: /probe/metrics/resourcegraph 
          params:
            name: ["azure_sqldatabase"]
            subscription:
            - a75c7008-66c1-4373-a0f3-859abaefccdb
            resourceType: ["Microsoft.Sql/servers/databases"]
            filter: [where kind eq "v12.0,user"]
            metric:
            - dtu_consumption_percent
            - storage_percent
            interval: ["PT5M"]
            timespan: ["PT5M"]
            aggregation:
            - average
            - maximum
          static_configs:
          - targets: ["azure-metrics-exporter.azure-metrics:80"]
```

but I'm not getting any metrics back in Grafana, using `/probe/metrics/list` without the filter as above works fine. I have also tried with `filter: [where kind eq "/v12.0,user/"]` but again no results. I then tried the following

```yaml
        - job_name: azure-metrics-sqldatabase
          scrape_interval: 1m
          metrics_path: /probe/metrics/resourcegraph
          params:
            name: ["azure_sqldatabase"]
            subscription:
            - a75c7008-66c1-4373-a0f3-859abaefccdb
            resourceType: ["Microsoft.Sql/servers/databases"]
            metric:
            - dtu_consumption_percent
            - storage_percent
            interval: ["PT5M"]
            timespan: ["PT5M"]
            aggregation:
            - average
            - maximum
          static_configs:
          - targets: ["azure-metrics-exporter.azure-metrics:80"]
```

which does indeed work. The filter I'm supplying appears to work in Azure portal resource graph explorer but not accepted when given through metrics exporter. Am I passing in the value incorrectly?
