### ISSUE TITLE
can you give demo about how to get aks and sqlserver metrics to prometheus

### ISSUE THREAD

**Issue by dyg070115** [webdevops/azure-metrics-exporter#14]

**Comment by dyg070115** [comment]
we need to export the azure monitor metrics data to promethues, we find azure-metrics-exporter: https://github.com/webdevops/azure-metrics-exporter

I need to get the metrics data of aks and azure SQL and save it in the self-built prometheus (prometheus installed in the azure vm). 
Can the azure-exporter configuration provide a demo?

Remarks: 
   Because my account does not have all permissions, there are some required parameters which I am not sure if I can see them. 
   If azure_exporter needs specific parameters, I need to apply for permissions separately.

**Comment by mblaschke** [comment]
you find the list of all supported metrics here:

- sql server: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftsqlserversdatabases
- aks: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcontainerservicemanagedclusters

not tested example:
```
- job_name: azure-metrics-aks
  scrape_interval: 1m
  metrics_path: /probe/metrics/list
  params:
    name: ["my_own_metric_name"]
    subscription:
    - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    resourceType: ["Microsoft.ContainerService/managedClusters"]
    metric:
    - cluster_autoscaler_cluster_safe_to_autoscale 
    - cluster_autoscaler_scale_down_in_cooldown
    - cluster_autoscaler_unneeded_nodes_count 
    interval: ["PT1H"]
    timespan: ["PT1H"]
    aggregation:
    - average
    - count
  static_configs:
  - targets: ["azure-metrics:8080"]
```

it depends from which resources, what metrics and which dimensions you want to fetch.
all information (except the supported intervals) you find in the microsoft support document mentioned above.

i'm thinking about providing a small webui to help with getting the correct information as azure really make that easy.
