### ISSUE TITLE
Gaps in metrics

### ISSUE THREAD

**Issue by ronyrv13** [webdevops/azure-metrics-exporter#18]
Hello Team,

I am facing a issue while implementing this metric-exporter, i am getting lot of gaps in the metrics.
i checked the same for several azure metrics, and i found that some of them have less one & some of them has huge gaps.
following is scrape config used -

`       - job_name: azure-metrics-virtualmachines
          scrape_interval: 5m
          metrics_path: /probe/metrics/list
          params:
            name:
              - azure_virtualmachines
            subscription:
              - ***********************************
            resourceType:
              - Microsoft.Compute/virtualMachines
            metric:
              - Percentage CPU
            interval: ["PT5M"]
            timespan: ["PT5M"]
            aggregation:
              - average
              - total
              - count
          static_configs:
          - targets: ["azure-metrics:8080"]`

There is no failure found in metric exporter logs/metrics neither with prometheus.
Tested the same at thanos-query as well.

Can you please help me with this?

![image](https://user-images.githubusercontent.com/34336227/157040712-62484c8d-7a28-4665-abd7-9ad62054b34d.png)

**Comment by mblaschke** [comment]
you get these gaps because you only scrape every 5 minutes

possible solutions:
- using eg `avg_over_time()` in the query
- scrape every 30seconds and enable caching. so let the azure-metrics-exporter scrape the metrics every 5 minutes and cache them 5 minutes

**Comment by ronyrv13** [comment]
Sorry mblaschke, my Bad, those output was with below config-

- scrape_interval: 1m
- interval: ["PT1M"]
- timespan: ["PT1M"]

after changing all of them to 5m i got below output where gaps were missing but data seems incorrect in comparison with azure portal dashboard.

![image](https://user-images.githubusercontent.com/34336227/157048977-db11ade9-5ab8-45de-9813-107875134809.png)

**Comment by ronyrv13** [comment]
Hello mblaschke

I got rid of gaps with below configuration -

       - job_name: azure-metrics-virtualmachines-scalesets
          scrape_interval: 1m
          metrics_path: /probe/metrics/list
          params:
            name:
              - azure_metric_machines_disk_scalesets
            subscription:
              - ***************************************
            resourceType:
              - Microsoft.Compute/virtualmachineScaleSets
            metric:
              - Data Disk IOPS Consumed Percentage
              - Data Disk Bandwidth Consumed Percentage
              - Data Disk Max Burst Bandwidth
              - Data Disk Max Burst IOPS
              - Data Disk Read Operations/Sec
              - Data Disk Read Bytes/sec
              - Data Disk Write Operations/Sec
              - Data Disk Write Bytes/sec
            interval: ["PT5M"]
            timespan: ["PT5M"]
            aggregation:
              - average
              - total
              - count
            metricFilter: ["VMName eq '*' and LUN eq '*'"]
          static_configs:
          - targets: ["azure-metrics:8080"]

But as i said there is mismatch in metrics values, you can find the same in below attached SS -

Here in azure dash SS you can find that, there was hike 1.28/s at 04:45 PM which never recorded in prometheus !.
In Grafana SS you can find that there was hike 04:51 PM but with value of 0.639.
There is diff in value (in comparison with azure) & 5min delay as well.

please help me with this !

<img width="955" alt="azure_dash" src="https://user-images.githubusercontent.com/34336227/157233633-c09eb202-e707-4664-8cce-0755f63bb289.png">

<img width="956" alt="grafana_dash" src="https://user-images.githubusercontent.com/34336227/157233644-4157b45b-fe5f-4702-8e00-45769519d0dc.png">

**Comment by mblaschke** [comment]
You're using 5min intervals where the Azure portal graph is using 1min intervals.

So you scrape it every (if no cache is enabled) every minute and you get the average value from the last 5 minutes.

**Comment by ronyrv13** [comment]
Hello mblaschke,
First of all Thank you so much for consistent reply and help.

Whenever i use below config (shortened) -
```
      scrape_interval: 1m
      metrics_path: /probe/metrics/list
        interval: ["PT1M"]
        timespan: ["PT1M"]
```
**I get gaps in metrics.**

and whenever i use 
```
      scrape_interval: 5m
      metrics_path: /probe/metrics/list
        interval: ["PT5M"]
        timespan: ["PT5M"]
```
**I get data mismatch.**

- Correct me if I am wrong, cache is by default enabled, right?

- if I mention timespan: ["PT5M"] then cache duration will also be 5m , right?

- Can you please suggest a suitable scrape config, which will resolve both the issue?..

**Comment by mblaschke** [comment]
You have to enable caching with either `--enable-caching` or env var `ENABLE_CACHING=1`.
When caching is enabled you have to set the scrape_interval to eg. `30s` or `1m`, otherwise you never use the cache.

The metrics are cached inside the exporter but you still have to fetch them from prometheus so you don't have gaps.

**Comment by ronyrv13** [comment]
ok Thanks for the quick response.
let me enable the caching and try with 
```
      scrape_interval: 1m
      metrics_path: /probe/metrics/list
        interval: ["PT1M"]
        timespan: ["PT1M"]
```

**Comment by mblaschke** [comment]
if you set your timespan to 1m and scrape 1m you don't need caching (because the cache would be only valid for 1m)

use case is:
- scrape_interval is set to 30s for all metrics
- if you set interval to 1m, metrics are fetched from Azure on every second scrape
- if you set interval to 30m, metrics are fetched from Azure on every 60th scrape

there are resources (eg DNS Zones) which are not providing metrics on minute base or you want to avoid ratelimit so you can set the timespan to a higher number

 you also could set the cache to a manual duration but most of the time that doesn't make sense.

**Comment by mblaschke** [comment]
example for dns zones:

```
      resourceType: ["Microsoft.Network/dnszones"]
      metric:
        - QueryVolume
        - RecordSetCapacityUtilization
        - RecordSetCount
      interval: [PT6H]
      timespan: [PT6H]
      cache: [30m]
```

if scraped every 30 seconds the metrics will stay in the cache for 30 minutes and then are fetched again from the Azure API so reducing the load Azure and avoid the ratelimit.

**Comment by ronyrv13** [comment]
ok, in that case below config should'nt give any gaps, but it's giving gaps.
 ```
       - job_name: azure-metrics-virtualmachines
          scrape_interval: 1M
          metrics_path: /probe/metrics/list
          params:
            name:
              - azure_virtualmachines
            subscription:
              - ******************************
            resourceType:
              - Microsoft.Compute/virtualMachines
            metric:
              - Percentage CPU
            interval: ["PT1M"]
            aggregation:
              - average
              - total
              - count
          static_configs:
          - targets: ["azure-metrics:8080"]
```
![image](https://user-images.githubusercontent.com/34336227/158174250-35793f02-ef7b-4fed-9f42-bf6ac4bc1ad6.png)
