### ISSUE TITLE
Querying multi dimensions in a single job 

### ISSUE THREAD

**Issue by manvitha9347** [webdevops/azure-metrics-exporter#21]
Hi,
I am working on config to get metrics from multi dimension from a single resource type
my config looks like this

```
- job_name: azure-metrics-example-dimensions
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: /probe/metrics/list
    params:
      template:
        - 'azuremetricsexplist_{metric}_{aggregation}_{unit}'
      cache:
        - 5s
      subscription:
        - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      resourceType:
        - Microsoft.DocumentDB/databaseAccounts
      metric:
        - ServerSideLatency
      interval: ["PT1M"]
      timespan: ["PT1M"]
      aggregation:
        - average
      metricFilter:
        - DatabaseName eq 'mydb' and CollectionName eq '*' and OperationType eq '*' and ConnectionMode eq '*'
    static_configs:
      - targets: ["172.17.0.2:8080"]
```

 when i use this config, there is a mismatch of data between azure and exporter data
 is there a way to specify all dimensions(CollectionName,OperationType,ConnectionMode)of a particular metric(Server side latency) in a single job name ? 
can you help me with this? @mblaschke
