### ISSUE TITLE
Splitting metrics by source

### ISSUE THREAD

**Issue by MostefaKamalLala** [webdevops/azure-metrics-exporter#22]
Hello,  I managed to make everything work in with my prometheus stack however I couldn't find how to split a metric like it's possible to do in grafana or Azure.
Basically I want to split my node_cpu_usage_percentage by host. 
Is there something to add in params or a special way to write it in the filter?
Thank  you
![image](https://user-images.githubusercontent.com/56651912/167021559-f555a10d-c78e-4f5c-8bee-04f2972b2870.png)

**Comment by mblaschke** [comment]
What you're looking for is the dimension support:
https://github.com/webdevops/azure-metrics-exporter#storageaccount-metric-namespace-and-dimension-support

**Comment by MostefaKamalLala** [comment]
Thank you @mblaschke I was misleaded by the the value in Azure UI which is host but in reality the dimension is node when I refered to the list of supported metrics following your guidance. Thank you very much!

**Comment by MostefaKamalLala** [comment]
I tried it out it's almost working but I found another issue, the result is different from Azure Monitor UI. I'm missing nodes from my second nodepool.

```yaml
scrape_configs:
  - job_name: azure-metrics-example
    scrape_interval: 1m
    metrics_path: /probe/metrics/list
    params:
      name:
        - azure-metric
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      subscription:
        - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      resourceType:
        - Microsoft.KeyVault/vaults
      metric:
        - Availability
        - ServiceApiHit
        - ServiceApiLatency
      interval:
        - PT1H
      timespan:
        - PT1H
      aggregation:
        - average
        - total
        - count
      metricTop:
        - 10
    static_configs:
      - targets:
          - url-to-your-azure-metrics-exporter-instance
```

I only get results from my linux vmss but i'm supposed to get it too from windows vmss.

**Comment by mblaschke** [comment]
> Thank you @mblaschke I was misleaded by the the value in Azure UI which is host but in reality the dimension is node when I refered to the list of supported metrics following your guidance. Thank you very much!

one of the problem for Azure Monitor: the bad documentation and that Azure portal is using different terms :(

> I only get results from my linux vmss but i'm supposed to get it too from windows vmss.

you're sharing the config example for keyvaults? 🤔

**Comment by MostefaKamalLala** [comment]
@mblaschke Updated. I found the issue. I was seeing the metrics on the vmss metrics namespace  in the UI of azure which is different from the managesdCluster metrics namespace. For some reasons, It's not returning all the nodes from the latest.

**Comment by MostefaKamalLala** [comment]
Got it working with your exporter finally. It was all about querying the right place. It was a pain finding it.
Here is my final working configuration:

```yaml
scrape_configs:
  - job_name: azure-metrics-example
    scrape_interval: 1m
    metrics_path: /probe/metrics/list
    params:
      name:
        - azure_metric
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      subscription:
        - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      resourceType:
        - Microsoft.ContainerService/managedClusters
      metricNamespace:
        - insights.container/nodes
      metric:
        - cpuUsagePercentage
      interval:
        - PT1H
      timespan:
        - PT1H
      aggregation:
        - average
      metricFilter:
        - host eq '*'
      metricTop:
        - 20
    static_configs:
      - targets:
          - url-to-your-azure-metrics-exporter-instance
```
