### ISSUE TITLE
Authentication in AKS

### ISSUE THREAD

**Issue by NosIreland** [webdevops/azure-metrics-exporter#28]
Hi,
I am trying to run exporter in AKS. I have simple config:
```
- job_name: azure-metrics
  metrics_path: /probe/metrics/list
  params:
    name:
      - azure_virtualmachines
    subscription:
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    resourceType:
      - Microsoft.Compute/virtualMachines
    metric:
      - Percentage CPU
    interval: [ "PT1M" ]
    timespan: [ "PT1M" ]
    aggregation:
      - average
      - total
      - count
  static_configs:
  - targets: ["azure-metrics-exporter:8080"]
```
I can access /metrics but scraping does not work, keep getting `context deadline exceeded` 
On the pod itself I see: 
`{"file":"/go/src/github.com/webdevops/azure-metrics-exporter/metrics/servicediscovery.go:131","func":"metrics.(*AzureServiceDiscovery).FindSubscriptionResources","level":"error","msg":"servicediscovery failed: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resources?%24filter=resourceType+eq+%27Microsoft.Compute%2FvirtualMachines%27\u0026api-version=2020-10-01: StatusCode=404 -- Original Error: adal: Refresh request failed. Status Code = '404'. Response body: getting assigned identities for pod monitoring/azure-metrics-exporter-54d9559c8b-26p6q in CREATED state failed after 16 attempts, retry duration [5]s, error: \u003cnil\u003e. Check MIC pod logs for identity assignment errors\n Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01\u0026resource=https%3A%2F%2Fmanagement.azure.com%2F","paramAggregation":["average","total","count"],"paramInterval":["PT1M"],"paramMetric":["Percentage CPU"],"paramName":["azure_virtualmachines"],"paramResourceType":["Microsoft.Compute/virtualMachines"],"paramSubscription":["xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"],"paramTimespan":["PT1M"],"requestPath":"/probe/metrics/list"}`
I am using managed identity but I suspect the problem is with autentication. Does it work with managed identity?
Thank you
