### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by grzesuav** [webdevops/azure-metrics-exporter#32]
Hi,

I often see messages like 
`
{"file":"/go/src/github.com/webdevops/azure-metrics-exporter/metrics/prober.go:199","func":"metrics.(*MetricProber).collectMetricsFromTargets.func1.1.1","level":"warning","msg":"context deadline exceeded","paramAggregation":["average"],"paramInterval":["PT1M"],"paramMetric":["BitsInPerSecond","BitsOutPerSecond"],"paramMetricFilter":["DeviceRole eq '*'"],"paramName":["azure_express_route_circuit"],"paramResourceType":["Microsoft.Network/expressRouteCircuits"],"paramSubscription":["xxx"],"paramTemplate":["{name}_{metric}_{unit}"],"paramTimespan":["PT1M"],"requestPath":"/probe/metrics/list","resourceID":"/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Network/expressRouteCircuits/some-001"}
`
and scraping by prometheus fails.

So under the hood query to Azure API is timeouting ?  How can I debug/resolve this issue ?

**Comment by mblaschke** [comment]
Which version are you using and how often is this happening?

**Comment by grzesuav** [comment]
I was on `22.8.0`, today switched to `22.9.0`. 

About the frequency, it is happening quite often, I see `116` in the last 10 minutes

**Comment by mblaschke** [comment]
how many resources are you scraping? how have you defined concurrency?

how often do you scrape and what timeout have you defined in prometheus? do you hit this limit (see in your prometheus scrape metrics)?

**Comment by mblaschke** [comment]
btw: i'm thinking/working on a standalone mode where the azure-metrics-exporter fetches the metrics on it's own without active probing based on a configuration file

so you will not have any timeouts when scraping lots of resources

**Comment by grzesuav** [comment]
I set timeout on prometheus time to `30s` , I have several scrape jobs, grouped by resource , i.e. 
```yaml
  metrics_path: /probe/metrics/list
  scrape_interval: 5m
  scrape_timeout: 30s
  params:
    name: ["azure_virtual_machine-scale-set"]
    template: ["{name}_{metric}_{aggregation}_{unit}"]
    subscription:
    - {{ $scrape_target.subscription_id }}
    resourceType:
    - Microsoft.Compute/virtualmachineScaleSets
    metric:
    - Data Disk Bandwidth Consumed Percentage
    - Data Disk IOPS Consumed Percentage
    - Data Disk Used Burst BPS Credits Percentage
    - Data Disk Used Burst IO Credits Percentage
    - Data Disk Read Bytes/sec
    - Data Disk Write Bytes/sec
    - OS Disk Bandwidth Consumed Percentage
    - OS Disk IOPS Consumed Percentage
    - OS Disk Queue Depth
    interval: ["PT5M"]
    timespan: ["PT5M"]
    aggregation:
    - average
    metricFilter:
    - VMName eq '*' and LUN eq '*'
    metricTop: ["1000"]
    cache: ["5m"]
```
