### ISSUE TITLE
export Azure VM Insights

### ISSUE THREAD

**Issue by christianjedroCDT** [webdevops/azure-metrics-exporter#33]
Hello,

i´m currently trying to get detailed metrics about Memory and Disk from my Azure VMs. For this i´ve activated the Insights option in the Monitoring section of the virtual machine and choose Azure Monitor Agent.

I can also see the metrics in Log Analytics Workspace and in Azure Monitor -> Metrics. My question now is if there is any way to export those values with this exporter? The following config does not provide anything:

```yaml
  - job_name: azure-metrics-insights
    scrape_interval: 1m
    metrics_path: /probe/metrics/list
    params:
      name:
        - azure_metric
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      help:
        - Azure metric {metric} for {aggregation}
      subscription:
        - xxx
      resourceType:
        - Microsoft.Compute/virtualMachines
      interval:
        - PT1H
      timespan:
        - PT1H
      aggregation:
        - average
      metricTop:
        - 10
      metric:
      - Heartbeat
      metricNamespace:
      - insights.virtualmachine/Computer
    static_configs:
      - targets: ["metrics-exporter:8080"]
```

These are the Values and some more Information from Log Analytics Workspace:

![law-export](https://user-images.githubusercontent.com/100683342/195317454-4a9e13af-0dae-45f1-bca2-4c3cb480c257.png)

**Comment by christianjedroCDT** [comment]
Issue resovled:

Working Disk Example

```yaml
scrape_configs:
  - job_name: azure-metrics-example
    scrape_interval: 1m
    metrics_path: /probe/metrics/list
    params:
      name:
        - azure-metric
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      subscription:
        - 1112b239-2b8e-44d7-8a44-7c9c8ca147c0
      resourceType:
        - Microsoft.Compute/virtualMachines
      metricNamespace:
        - insights.virtualmachine
      metric:
        - LogicalDisk\FreeSpacePercentage
      interval:
        - PT5M
      timespan:
        - PT5M
      aggregation:
        - average
      metricFilter:
        - DiskMountId eq '*'
      metricTop:
        - 10
    static_configs:
      - targets:
          - url-to-your-azure-metrics-exporter-instance
```

Working Memory Example
```yaml
scrape_configs:
  - job_name: azure-metrics-example
    scrape_interval: 1m
    metrics_path: /probe/metrics/list
    params:
      name:
        - azure-metric
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      subscription:
        - 1112b239-2b8e-44d7-8a44-7c9c8ca147c0
      resourceType:
        - Microsoft.Compute/virtualMachines
      metricNamespace:
        - insights.virtualmachine
      metric:
        - Memory\AvailableBytes
      interval:
        - PT5M
      timespan:
        - PT5M
      aggregation:
        - average
      metricTop:
        - 10
    static_configs:
      - targets:
          - url-to-your-azure-metrics-exporter-instance
```
```
