### ISSUE TITLE
Automatic retry for SubscriptionRequestsThrottled errors.

### ISSUE THREAD

**Issue by jkroepke** [webdevops/azure-metrics-exporter#36]
Hi all, 

i would like to ask if its possible to implement a automatic retry mechanism, if a SubscriptionRequestsThrottled answers appears.

Sometime, we get errors like this:

```
"GET https://management.azure.com/subscriptions/xxx/resourceGroups/xxxx/providers/Microsoft.Compute/virtualMachines/xxxx//providers/Microsoft.Insights/metrics\n--------------------------------------------------------------------------------\nRESPONSE 429: 429 Too Many Requests\nERROR CODE: SubscriptionRequestsThrottled\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"SubscriptionRequestsThrottled\",\n    \"message\": \"Number of requests for subscription '6fb867d5-d552-4dbe-9f6a-7a151b6292aa' and operation 'GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINES/PROVIDERS/MICROSOFT.INSIGHTS/METRICS' exceeded the backend storage limit. Please try again after '0' seconds.\"\n  }\n}\n--------------------------------------------------------------------------------\n"
```

**Comment by mblaschke** [comment]
can you give me the full line? and did you see panics?

azure-sdk-for-go actually already provide proper retry mechanisms inside so the applications don't have to deal with it.

**Comment by jkroepke** [comment]
```
{"file":"/go/src/github.com/webdevops/azure-metrics-exporter/probe_metrics_resourcegraph.go:67","func":"main.probeMetricsResourceGraphHandler","level":"error","msg":"POST https://management.azure.com/providers/Microsoft.ResourceGraph/resources\n--------------------------------------------------------------------------------\nRESPONSE 429: 429 Too Many Requests\nERROR CODE: RateLimiting\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"RateLimiting\",\n    \"message\": \"Please provide below info when asking for support: timestamp = 2022-11-23T04:45:38.1385432Z, correlationId = eeb67e21-2cb9-4856-9117-b22901cec469.\",\n    \"details\": [\n      {\n        \"code\": \"RateLimiting\",\n        \"message\": \"Client application has been throttled and should not attempt to repeat the request until an amount of time has elapsed. Please see https://aka.ms/resourcegraph-throttling for help.\"\n      }\n    ]\n  }\n}\n--------------------------------------------------------------------------------\n","paramAggregation":["average"],"paramHelp":["Azure metrics for {metric} with aggregation {aggregation} as {unit}"],"paramInterval":["PT1M"],"paramMetric":["LogicalDisk\\FreeSpaceBytes","LogicalDisk\\FreeSpacePercentage"],"paramMetricFilter":["DiskMountId eq '*'"],"paramMetricNamespace":["insights.virtualmachine"],"paramName":["azure_virtual_machine"],"paramResourceType":["Microsoft.Compute/virtualMachines"],"paramSubscription":["xxx"],"paramTemplate":["{name}_{metric}_{aggregation}_{unit}"],"paramTimespan":["PT1M"],"requestPath":"/probe/metrics/resourcegraph"}
--

{"file":"/go/src/github.com/webdevops/azure-metrics-exporter/metrics/prober.go:199","func":"metrics.(*MetricProber).collectMetricsFromTargets.func1.1.1","level":"warning","msg":"GET https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachines/xxx//providers/Microsoft.Insights/metrics\n--------------------------------------------------------------------------------\nRESPONSE 429: 429 Too Many Requests\nERROR CODE: SubscriptionRequestsThrottled\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"SubscriptionRequestsThrottled\",\n    \"message\": \"Number of requests for subscription 'xxx' and operation 'GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINES/PROVIDERS/MICROSOFT.INSIGHTS/METRICS' exceeded the backend storage limit. Please try again after '0' seconds.\"\n  }\n}\n--------------------------------------------------------------------------------\n","paramAggregation":["average"],"paramHelp":["Azure metrics for {metric} with aggregation {aggregation} as {unit}"],"paramInterval":["PT1M"],"paramMetric":["Memory\\AvailableBytes","Memory\\AvailablePercentage","Processor\\UtilizationPercentage"],"paramMetricNamespace":["insights.virtualmachine"],"paramName":["azure_virtual_machine"],"paramResourceType":["Microsoft.Compute/virtualMachines"],"paramSubscription":["xxx"],"paramTemplate":["{name}_{metric}_{aggregation}_{unit}"],"paramTimespan":["PT1M"],"requestPath":"/probe/metrics/resourcegraph","resourceID":"/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachines/xxx"}
```

**Comment by jkroepke** [comment]
Hi,

70 machine, 1 minute interval, 3 requests for each machine (normal metrics, insight metrics, insight metrics + disk dimension)

we could solved our issue for now by enable the cache on the resource manager service discovery. Atleast for now.

Our use case may be a bit strange, but we are need to fetch fine-granular metrics from Azure Monitor (and Cloudwatch) 
 (only important metrics) and store them into our prometheus.

Not sure, if a background fetch help if, if the time interval must be still a minute.

**Comment by mblaschke** [comment]
Do you use an own serviceprincipal or is it used for other services as well?
Do you monitor the azure ratelimit metrics? do you hit them anywhere?

Is there any reason to disable the servicediscovery cache? do you constantly delete and create VMs?

**Comment by jkroepke** [comment]
> Do you use an own serviceprincipal or is it used for other services as well?

Its also used by a Grafana Data Source for Azure Monitor, but thats is rarely used.

> Do you monitor the azure ratelimit metrics?

Ye, azure-metrics-exporter exposes rate limits in prometheus format, but we never hit zero there.

Azure replies something like `Please try again after '0' seconds.` I guess, it is a issue with some peaks.

> Is there any reason to disable the servicediscovery cache? do you constantly delete and create VMs?

No. caching is fine for us.

**Comment by jkroepke** [comment]
Before enabling cache:
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/1560587/204742380-2610a1c9-2819-4461-9048-9e86a64a3922.png">

After enabling cache:
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/1560587/204741488-8026a079-70d2-4710-b29d-393e0f00acd5.png">

**Comment by mblaschke** [comment]
If you don't cache servicediscovery every scape will fetch the list of resources. So if you scrape 3 different metric sets for VMs the exporter is fetching the resource list 3 times. This is solved using the servicediscovery cache.

If you use resourcegraph for servicediscovery you even avoid subscription api calls.

Will still check the behaviour of the azure-sdk-for-go.

**Comment by jkroepke** [comment]
The Insights Metrics call to Azure Monitor counts as subscription call, too?

**Comment by mblaschke** [comment]
Hm.. i think so but not fully sure.

Can you post the scrape configuration? To check if it can be optimized.

**Comment by jkroepke** [comment]
At least by reading the error message

> Number of requests for subscription 'xxxxxxx-xxxx-xxxx-xxxx-7a151b6292aa' and operation 'GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINES/PROVIDERS/MICROSOFT.INSIGHTS/METRICS' exceeded the backend storage limit. Please try again after '0' seconds.

I feel like the metrics requests counts as subscription call, since they are in a scope of a subscription.

**Comment by mblaschke** [comment]
can you still post your configuration? just to get insights how you're scraping your metrics.

**Comment by jkroepke** [comment]
If you now how we are able combine metric calls with different dimensions, please let me know.

```yaml
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: http
    - interval: 1m
      metricRelabelings:
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $3
          sourceLabels:
            - resourceID
          targetLabel: resourceType
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $4
          sourceLabels:
            - resourceID
          targetLabel: resourceName
        - action: replace
          sourceLabels:
            - resourceName
          targetLabel: vmName
      params:
        aggregation:
          - average
        help:
          - Azure metrics for {metric} with aggregation {aggregation} as {unit}
        interval:
          - PT1M
        metric:
          - LogicalDisk\FreeSpaceBytes
          - LogicalDisk\FreeSpacePercentage
        metricFilter:
          - DiskMountId eq '*'
        metricNamespace:
          - insights.virtualmachine
        name:
          - azure_virtual_machine
        resourceType:
          - Microsoft.Compute/virtualMachines
        subscription:
          - xxxxxxxx-xxxx-400b-bfa5-df05fee38279
        template:
          - '{name}_{metric}_{aggregation}_{unit}'
        timespan:
          - PT1M
      path: /probe/metrics/resourcegraph
      port: http
      scrapeTimeout: 50s
    - interval: 1m
      metricRelabelings:
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $3
          sourceLabels:
            - resourceID
          targetLabel: resourceType
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $4
          sourceLabels:
            - resourceID
          targetLabel: resourceName
        - action: replace
          sourceLabels:
            - resourceName
          targetLabel: vmName
      params:
        aggregation:
          - average
        help:
          - Azure metrics for {metric} with aggregation {aggregation} as {unit}
        interval:
          - PT1M
        metric:
          - Memory\AvailableBytes
          - Memory\AvailablePercentage
          - Processor\UtilizationPercentage
        metricNamespace:
          - insights.virtualmachine
        name:
          - azure_virtual_machine
        resourceType:
          - Microsoft.Compute/virtualMachines
        subscription:
          - xxxxxxxx-xxxx-400b-bfa5-df05fee38279
        template:
          - '{name}_{metric}_{aggregation}_{unit}'
        timespan:
          - PT1M
      path: /probe/metrics/resourcegraph
      port: http
      scrapeTimeout: 50s
    - interval: 1m
      metricRelabelings:
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $3
          sourceLabels:
            - resourceID
          targetLabel: resourceType
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $4
          sourceLabels:
            - resourceID
          targetLabel: resourceName
        - action: replace
          sourceLabels:
            - resourceName
          targetLabel: vmName
      params:
        aggregation:
          - average
        help:
          - Azure metrics for {metric} with aggregation {aggregation} as {unit}
        interval:
          - PT1M
        metric:
          - vmAvailabilityMetric
        name:
          - azure_virtual_machine
        resourceType:
          - Microsoft.Compute/virtualMachines
        subscription:
          - xxxxxxxx-xxxx-400b-bfa5-df05fee38279
        template:
          - '{name}_{metric}_{aggregation}_{unit}'
        timespan:
          - PT1M
      path: /probe/metrics/resourcegraph
      port: http
      scrapeTimeout: 50s
    - interval: 1m
      metricRelabelings:
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $3
          sourceLabels:
            - resourceID
          targetLabel: resourceType
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $4
          sourceLabels:
            - resourceID
          targetLabel: resourceName
        - action: replace
          sourceLabels:
            - resourceName
          targetLabel: vmName
        - action: replace
          sourceLabels:
            - dimension
          targetLabel: vmName
      params:
        aggregation:
          - average
        help:
          - Azure metrics for {metric} with aggregation {aggregation} as {unit}
        interval:
          - PT1M
        metric:
          - LogicalDisk\FreeSpaceBytes
          - LogicalDisk\FreeSpacePercentage
        metricFilter:
          - VmName eq '*' and DiskMountId eq '*'
        metricNamespace:
          - insights.virtualmachine
        name:
          - azure_virtual_machine
        resourceType:
          - Microsoft.Compute/virtualMachineScaleSets
        subscription:
          - xxxxxxxx-xxxx-400b-bfa5-df05fee38279
        template:
          - '{name}_{metric}_{aggregation}_{unit}'
        timespan:
          - PT1M
      path: /probe/metrics/resourcegraph
      port: http
      scrapeTimeout: 50s
    - interval: 1m
      metricRelabelings:
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $3
          sourceLabels:
            - resourceID
          targetLabel: resourceType
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $4
          sourceLabels:
            - resourceID
          targetLabel: resourceName
        - action: replace
          sourceLabels:
            - resourceName
          targetLabel: vmName
        - action: replace
          sourceLabels:
            - dimension
          targetLabel: vmName
      params:
        aggregation:
          - average
        help:
          - Azure metrics for {metric} with aggregation {aggregation} as {unit}
        interval:
          - PT1M
        metric:
          - Memory\AvailableBytes
          - Memory\AvailablePercentage
          - Processor\UtilizationPercentage
        metricFilter:
          - VmName eq '*'
        metricNamespace:
          - insights.virtualmachine
        name:
          - azure_virtual_machine
        resourceType:
          - Microsoft.Compute/virtualMachineScaleSets
        subscription:
          - xxxxxxxx-xxxx-400b-bfa5-df05fee38279
        template:
          - '{name}_{metric}_{aggregation}_{unit}'
        timespan:
          - PT1M
      path: /probe/metrics/resourcegraph
      port: http
      scrapeTimeout: 50s
    - interval: 1m
      metricRelabelings:
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $3
          sourceLabels:
            - resourceID
          targetLabel: resourceType
        - action: replace
          regex: /subscriptions/(.+)/resourcegroups/(.+)/providers/(.+/.+)/(.+)
          replacement: $4
          sourceLabels:
            - resourceID
          targetLabel: resourceName
        - action: replace
          sourceLabels:
            - resourceName
          targetLabel: vmName
        - action: replace
          sourceLabels:
            - dimension
          targetLabel: vmName
      params:
        aggregation:
          - average
        help:
          - Azure metrics for {metric} with aggregation {aggregation} as {unit}
        interval:
          - PT1M
        metric:
          - vmAvailabilityMetric
        metricFilter:
          - VmName eq '*'
        name:
          - azure_virtual_machine
        resourceType:
          - Microsoft.Compute/virtualMachineScaleSets
        subscription:
          - xxxxxxxx-xxxx-400b-bfa5-df05fee38279
        template:
          - '{name}_{metric}_{aggregation}_{unit}'
        timespan:
          - PT1M
      path: /probe/metrics/resourcegraph
      port: http
      scrapeTimeout: 50s
```
