### ISSUE TITLE
Getting historical data from Azure Monitor

### ISSUE THREAD

**Issue by jkroepke** [webdevops/azure-metrics-exporter#42]
Hi,

currently, I'm try to implement Backup monitor. Recovery Service publish Metrics through Azure Monitor.

If a Backup Job ends, a metric `BackupHealthEvent` with multiple dimensions are published to Azure Monitor. Here is a screenshot of Azure Monitor

<details>
<summary>Azure Monitor </summary>

![image](https://user-images.githubusercontent.com/1560587/214873079-398fb09f-bcd4-4636-8032-102882c3303c.png)

</details>

Azure Monitor exporter allows me only to fetch the lastest values from Monitor. 

Set timespan to P1D is a workaround, but I'm losing the information, when the metrics hits 1 (to get the date of the backup job)

The Open Metrics format supported dated metrics by append the timestamp on it. What I would like to see is the information like export all metrics points in last `timespan` instead just the lastest value.

<details>
<summary>Config</summary>

```
scrape_configs:
  - job_name: azure-metrics-example
    scrape_interval: 1m
    metrics_path: /probe/metrics/resourcegraph
    params:
      name:
        - azure_metric
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      help:
        - Azure metric {metric} for {aggregation}
      subscription:
        - 05d740d9-f073-4e49-be7a-3913027a6861
      resourceType:
        - Microsoft.RecoveryServices/vaults
      metric:
        - BackupHealthEvent
      interval:
        - PT1M
      timespan:
        - P1D
      aggregation:
        - count
      metricFilter:
        - healthStatus eq '*' and backupInstanceName eq '*'
      metricTop:
        - 10
    static_configs:
      - targets:
          - url-to-your-azure-metrics-exporter-instance
```

</details>
