### ISSUE TITLE
Support for multi-resource queries

### ISSUE THREAD

**Issue by jkroepke** [webdevops/azure-metrics-exporter#44]
Hi,

Azure Monitor is offers multi-resource queries (preview). 

https://azure.microsoft.com/en-us/updates/select-multiple-resources-in-azure-monitor-log-analytics/

My hope is to reduce the amount of calls to prevent rate-limit issues.

On Browser leve following request was used to gain multiple metrics:

> POST /subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/providers/microsoft.Insights/metrics?timespan=2023-02-19T15:30:00.000Z/2023-02-20T15:35:00.000Z&interval=PT5M&metricnames=CPU Credits Consumed&aggregation=average&metricNamespace=microsoft.compute%2Fvirtualmachines&top=10&orderby=average desc&autoadjusttimegrain=true&validatedimensions=false&api-version=2021-05-01&region=westus3

> filter: "Microsoft.ResourceId eq '/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/resourceGroups/default/providers/Microsoft.Compute/virtualMachines/bastion-win' or Microsoft.ResourceId eq '/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/resourceGroups/default/providers/Microsoft.Compute/virtualMachines/bastion-linux'"

I was trying to replicate it, but I had no success

```
scrape_configs:
  - job_name: azure-metrics-example
    scrape_interval: 1m
    metrics_path: /probe/metrics/resource
    params:
      name:
        - azure_metric
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      help:
        - Azure metric {metric} for {aggregation}
      subscription:
        - 6fb867d5-d552-4dbe-9f6a-7a151b6292aa
      target:
        - /subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a
      metricNamespace:
        - microsoft.compute/virtualmachines
      metric:
        - Available Memory Bytes
      interval:
        - PT1H
      timespan:
        - PT1H
      aggregation:
        - average
        - total
        - count
      metricFilter:
        - Microsoft.ResourceId eq '/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/resourceGroups/default/providers/Microsoft.Compute/virtualMachines/bastion-win' or Microsoft.ResourceId eq '/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/resourceGroups/default/providers/Microsoft.Compute/virtualMachines/bastion-linux'
      metricTop:
        - 10
    static_configs:
      - targets:
          - url-to-your-azure-metrics-exporter-instance
```

> WARN[0089]/home/runner/work/azure-metrics-exporter/azure-metrics-exporter/metrics/prober.go:120 metrics.(*MetricProber).AddTarget unable to parse resource id: parsing failed for /subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a. Invalid resource Id format  paramAggregation="[average,total,count]" paramHelp="[Azure metric {metric} for {aggregation}]" paramInterval="[PT1H]" paramMetric="[Available Memory Bytes]" paramMetricFilter="[Microsoft.ResourceId eq '/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/resourceGroups/default/providers/Microsoft.Compute/virtualMachines/bastion-win' or Microsoft.ResourceId eq '/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a/resourceGroups/default/providers/Microsoft.Compute/virtualMachines/bastion-linux']" paramMetricNamespace="[microsoft.compute/virtualmachines]" paramMetricTop="[10]" paramName="[azure_metric]" paramSubscription="[6fb867d5-d552-4dbe-9f6a-7a151b6292aa]" paramTarget="[/subscriptions/e1608e24-0728-4efd-ba5b-a05693b53c5a]" paramTemplate="[{name}_{metric}_{aggregation}_{unit}]" paramTimespan="[PT1H]" requestPath=/probe/metrics/resource

Aside from that, there where no support for service discovery

See. also: https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-dynamic-scope

Edit: It seems like its not availible in SDk, yet https://github.com/Azure/azure-sdk-for-go/issues/20039
