### ISSUE TITLE
Unable to fetch metrics which doesn't have dimension

### ISSUE THREAD

**Issue by logamanig** [webdevops/azure-metrics-exporter#45]
Hi,

Following config using helm chart is not working for me. It seems like metrics without dimensions is not working, I tried another configurationf for storage account only metrics with dimensions are exporteed and others ignored. Can you please help me on this?

Thank you!
```yaml
metricProbes:
      params:
        template: ["{name}_{metric}_{aggregation}_{unit}"]
        subscription:
          - xxx-xx-xx
      probes:
        - name: azuresql
          metrics_path: /probe/metrics/list
          interval: 30s
          params:
            name: ["az_sql"]
            filter: ["resourceType eq 'Microsoft.Sql/servers/databases'"]
            metric:
              - active_queries
              - allocated_data_storage
              - blocked_by_firewall
              - cache_hit_percent
              - cache_used_percent
              - cpu_limit
              - cpu_percent
              - cpu_used
              - app_memory_percent
              - app_cpu_percent
              - memory_usage_percent
            interval: ["PT30S"]
            timespan: ["PT30S"]
            aggregation:
              - average
              - total
              - maximum
 ```
