### ISSUE TITLE
Unable to extract metrics from managed cluster (AKS)

### ISSUE THREAD

**Issue by Giri0422** [webdevops/azure-metrics-exporter#46]
i tried deploy this on my aks cluster and i was able to extract metrics from resourcetype like keyvault.storageaccount,redis etc. when i did the same for Microsoft.ContainerService/managedClusters resourcetype i am not getting any results i have assigned monitoring reader role as well. can you please let me know if this exporter supports managed cluster resource type or am i wrong. can  you please help on this.

Job_config : 
```yaml
- job_name: azure-metrics-ContainerService
        scrape_interval: 1m
        metrics_path: /probe/metrics/list
        params:
          name: ["azure-metrics-ContainerService"]
          subscription:
          - "{{ .Values.subscriptionId }}"
          filter: ["(resourceGroup eq '{{ .Values.resourceGroup }}' or resourceGroup eq '{{ .Values.resourceGroup }}-aks') and resourceType eq 'Microsoft.ContainerService/managedClusters'"]
          metrics:
          - apiserver_current_inflight_requests
          - cluster_autoscaler_cluster_safe_to_autoscale
          - cluster_autoscaler_scale_down_in_cooldown
          - cluster_autoscaler_unneeded_nodes_count
          - cluster_autoscaler_unschedulable_pods_count
          - kube_node_status_allocatable_cpu_cores
          - kube_node_status_allocatable_memory_bytes
          - kube_node_status_condition
          - kube_pod_status_phase
          - kube_pod_status_ready
          - node_cpu_usage_millicores
          - node_cpu_usage_percentage
          - node_disk_usage_bytes
          - node_disk_usage_percentage
          - node_memory_rss_bytes
          - node_memory_rss_percentage
          - node_memory_working_set_bytes
          - node_memory_working_set_percentage
          - node_network_in_bytes
          - node_network_out_bytes
          interval: ["PT1M"]
          timespan: ["PT1M"]
          aggregation:
          - average
          - total
        static_configs:
        - targets: ["azure-metrics-exporter:8080"]
 ```
