### ISSUE TITLE
Metric gaps

### ISSUE THREAD

**Issue by AM-Dani** [webdevops/azure-metrics-exporter#47]
Hello Team,

We are trying to extract metrics from various resources (service bus, storage accounts, and VMs) and we are experiencing gaps several times a day in all of them. For some of these gaps, we clearly see that the problem is on Azure's side (QueryThrottledException), but for others, we don't see anything in the log entries or in the exporter's metrics. This is an example from today, for the ServiceBus:

![image](https://user-images.githubusercontent.com/129111242/228047140-c4cc99d9-8fa3-4a05-a031-564160d9601b.png)

azurerm_api_request_count (rate):
![image](https://user-images.githubusercontent.com/129111242/228047249-8d6e950d-016a-4a6e-b110-f5cefcd9ba36.png)

azurerm_api_request_bucket (30s):
![image](https://user-images.githubusercontent.com/129111242/228048123-6c43993d-cd7f-41e7-bd3b-343188e5fafb.png)

With the following configuration:
```
endpoints:
  - interval: 1m
    path: /probe/metrics/resourcegraph
    port: metrics
    scrapeTimeout: 55s
    params:
      name:
        - 'azure-metric'
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      subscription:         
        - '***************'
      resourceType:
        - 'Microsoft.ServiceBus/Namespaces'
      metric:
        - 'ActiveMessages'
        - 'DeadletteredMessages'
        - 'ScheduledMessages'
        - 'IncomingMessages'
        - 'OutgoingMessages'
      interval:
        - 'PT1M'
      timespan:
        - 'PT1M'
      aggregation:
        - 'average'
        - 'total'
      metricFilter:
        - EntityName eq '*'
      metricTop:
        - '500'
```

No failure found in the metrics exporter logs, and we have the same problems using '/probe/metrics/list' in other resources.

Can you please help me with this?
