### ISSUE TITLE
Question: is it possible to filter metrics by resource type and resource tags using the list probe endpoint ?

### ISSUE THREAD

**Issue by mbenabda** [webdevops/azure-metrics-exporter#51]
Hi there.
First, let me thank you for the awesome work you're doing providing this exporter.

I'd like to know if there's any way i can filter metrics using both resource type and resource tags ?
I'm pretty new to Azure metrics, so this may be straightforward, but i can't figure out how to do this

What i've tried so far:
- using the `resourceType` parameter with value `['Microsoft.EventHub/Namespaces']`, it works, but is only part of what i'm looking for
- using the `filter` parameter with value `tagName eq 'my_tag_name' AND tagValue eq 'my_tag_value'`, it works, but is only part of what i'm looking for
- using the `filter` parameter with value `resourceType eq 'Microsoft.EventHub/Namespaces'`, it also works, but is only part of what i'm looking for
- using both filters, separated with an `and` operator, does not work
- using both the `resourceType` and `filter` parameters does not work, there are mutualy exclusive
- The [Docs](https://learn.microsoft.com/en-us/rest/api/resources/resources/list#uri-parameters) state that 
  ```
  some properties can be combined when filtering resources, which include the following: substringof() and/or resourceType
  ```
  this suggests that some properties can NOT be combined as well, so i have tried combining `substringof()` and `resourceType`, to use one of the supported combinations, but without success

here's my scraping configuration:
```yaml
    interval: 1m
    path: /probe/metrics/list
    # https://github.com/webdevops/azure-metrics-exporter#probemetricslist-parameters
    params:
      subscription: ["${subscription_id}"]
      template: ["{name}_{metric}_{aggregation}"]
      name: ["azure_eventhub_namespaces"]
      #resourceType: ["Microsoft.EventHub/Namespaces"] # => works
      #filter: ["tagName eq 'env' AND tagValue eq '${env}'"] # => works
      #filter: ["resourceType eq 'Microsoft.EventHub/Namespaces'"] # => works
      #filter: ["tagName eq 'env' AND tagValue eq '${env}' and resourceType eq 'Microsoft.EventHub/Namespaces'"] # does not work
      filter: ["substringof('${env}',tagName) and resourceType eq 'Microsoft.EventHub/Namespaces'"] # does not work
      metric: 
      - ActiveConnections
      - IncomingMessages
      - OutgoingMessages
      aggregation:
      - total
```
any help appreciated, thank you !
