### ISSUE TITLE
Retrieve metrics from StorageAccount/Fileshares 

### ISSUE THREAD

**Issue by satare** [webdevops/azure-metrics-exporter#52]
Hi, 
First : thanks for this product, i'm using it a lot in my monitoring strategy, it's a very cool addition. 
People come see me to monitor fileshares usage, so i made a prometheus scrape config for that but can't make it work.

In one of my subscriptions, i have 2 storage accounts, with somes fileshares in them. 
I can reach the metrics from the fileshare with this scrape config : (thanks again for the UI ... game changer)

```yaml
scrape_configs:
  - job_name: azure-metrics-example
    scrape_interval: 1m
    metrics_path: /probe/metrics/resourcegraph
    params:
      name:
        - fs
      template:
        - '{name}_{metric}_{aggregation}_{unit}'
      help:
        - Azure metric {metric} for {aggregation}
      subscription:
        - 999-999-999-999-999999
      resourceType:
        - Microsoft.Storage/storageAccounts
      metric:
        - Availability
      interval:
        - PT1M
      timespan:
        - PT1M
      aggregation:
        - average
        - total
        - count
      metricTop:
        - 10
    static_configs:
      - targets:
          - url-to-your-azure-metrics-exporter-instance
```

But as soon as i add the
```yaml
      metricNamespace:
        - Microsoft.Storage/storageAccounts/fileServices
``` 
to this scrape config, i get a HTTP200 from the azure exporter, but no results at all.

Is there something i do wrong ? I take the exemple from the last section of the readme.

Thanks in advance, if someone can help me.
