### ISSUE TITLE
parameter "subscription" is missing

### ISSUE THREAD

**Issue by pavithra24** [webdevops/azure-metrics-exporter#59]
Below is my configuration for azure metrics exporter, when I browse `/probe/metrics/list `
I get this error **parameter "subscription" is missing**

   ```
 - job_name: azure-metrics-databases
      scrape_interval: 1m
      metrics_path: /probe/metrics/list
      params:
        name: ["azure-databases"]
        subscription:
        - xxx-xxx
        filter: ["resourceType eq 'Microsoft.DBforMySQL/servers'"]
        metric:
        - storage_used
        - storage_percent
        - connections_failed
        - cpu_percent
        - active_connections
        - network_bytes_egress
        - network_bytes_ingress
        interval: ["PT1M"]
        timespan: ["PT1M"]
        aggregation:
        - average
        - total
      static_configs:
      - targets: ["azure-metrics-exporter-webdevops.external-monitor.svc.cluster.local:8080"]
```
Please help me to fix this, I do see this on Prometheus dashboard 

azure_databases{aggregation="average", instance="azure-metrics-exporter-webdevops.external-monitor.svc.cluster.local:8080", interval="PT1M", job="azure-metrics-databases", metric="active_connections", resourceGroup="databases-rg", resourceID="/subscriptions/xxx-xxx/resourcegroups/databases-rg/providers/microsoft.dbformysql/servers/shopware-mysql", resourceName="shopware-mysql", subscriptionID="xxx-xxx", subscriptionName="dedicated", timespan="PT1M", unit="Count"}
