### ISSUE TITLE
Metrics not shown in prometheus for Backup Vault

### ISSUE THREAD

**Issue by cvallesi-kainos** [webdevops/azure-metrics-exporter#60]
Hi there,

I have successfully configured jobs to get metrics from Frontdoor or App Service but when trying to get metrics from Backup Vault, they simply aren't shown.

I generated the job configuration using the query builder in `/query` and verified that in prometheus the target is responding.
Checked the namespace logs for azure-metrics-exporter and cannot see any error, but when I try to see if the metrics generated by the job are there, the prometheus auto-complete is not showing up anything related to the job.

This is the configuration:

```
[...]
- job_name: azure-backup-vault
        scrape_interval: 1m
        metrics_path: /probe/metrics/list
        params:
          name:
            - azurerm_backup_vault
          template:
            - '{name}_{metric}_{aggregation}_{unit}'
          help:
            - Azure Backup Vault {metric} for {aggregation}
          subscription:
            - OMITTED
          resourceType:
            - Microsoft.DataProtection/BackupVaults
          metric:
            - BackupHealthEvent
            - RestoreHealthEvent
          interval:
            - PT1H
          timespan:
            - PT1H
          aggregation:
            - count
        static_configs:
          - targets:
              - azure-metrics-exporter.azure-metrics-exporter.svc.cluster.local:8080
```

Prometheus endpoint:
![image](https://github.com/webdevops/azure-metrics-exporter/assets/97892370/bef44b50-a232-4718-830e-f1c8d7a2573c)

Browsing metrics:
![image](https://github.com/webdevops/azure-metrics-exporter/assets/97892370/65349aa3-723a-4993-bf27-19028006daa6)

Is there anything that I maybe stupidly missing here? :|
