### ISSUE TITLE
How can I support this filter by RateLimitKey?

### ISSUE THREAD

**Issue by callumj** [webdevops/azure-metrics-exporter#62]
I want to break down BlockedCalls and Latency for a CognitiveServices metric by `RateLimitKey` which I have confirmed is possible via the ARM library:

```
res, err := client.List(ctx, "subscriptions/<SUB_ID>/resourceGroups/<GROUP>/providers/Microsoft.CognitiveServices/accounts/<ACCOUNT>", &armmonitor.MetricsClientListOptions{
		Interval:        to.Ptr("PT1M"),
		Metricnames:     to.Ptr("BlockedCalls,Latency"),
		Aggregation:     to.Ptr("Average"),
		Filter:          to.Ptr("RatelimitKey eq '*'"),
		ResultType:      nil,
		Metricnamespace: to.Ptr("Microsoft.CognitiveServices/accounts"),
	})
```

Translating this into:

```
- job_name: azure-metrics-cognitive-accounts-blocked-calls
  scrape_interval: 30s
  metrics_path: /probe/metrics/scrape
  params:
    name: ["microsoft_cognitive_services_accounts_blocked_calls"]
    subscription:
      - "<SUB_ID>"
    target:
      - "subscriptions/<SUB_ID>/resourceGroups/<GROUP>/providers/Microsoft.CognitiveServices/accounts/<ACCOUNT>",
    metricNamespace: ["Microsoft.CognitiveServices/accounts"]
    filter: ["RatelimitKey eq '*'"]
    metric:
    - BlockedCalls
    interval: ["PT1M"]
    timespan: ["PT1M"]
    aggregation:
    - total
  static_configs:
  - targets: ["localhost:8080"]
  ```

ends up with an error

```
{
  "error": {
    "code": "InvalidFilterInQueryString",
    "message": "Invalid $filter 'RatelimitKey eq '*'' specified in the query string."
  }
}
```

Presumably because it first wants to scrape the subscription list using `FindSubscriptionResources`. But I should not need that right?
