### ISSUE TITLE
Is it possible to specify the subscription and resource group in the azure-metrics-exporter config instead of Prometheus?

### ISSUE THREAD

**Issue by johnswarbrick-napier** [webdevops/azure-metrics-exporter#79]
I have two related issues:

(1) I want to specify the Azure subscription as an environment variable that is passed automatically to `azure-metrics-exporter` instead of specifying it manually in the Prometheus scrape config;

(2) I want to specify the resource group as an environment variable that is password automatically to `azure-metrics-monitor` so the results are always filtered to the given resource group name;

I tried passing the subscription ID from a Kubernetes secret already, but it seems I still need to specify the subscription ID in the Prometheus scape config?

```
   - name: AZURE_SERVICEDISCOVERY_SUBSCRIPTION_ID
     valueFrom:
       secretKeyRef:
         key: subscription
         name: azure-resource-details
```

And there doesn't seem to be any method of specifying the resource group as an environment variable at all in the docs?

The reason is that I am currently using an identical Prometheus scraping configuration across more than 100 clusters, and I don't want to manually specify the subscription ID or resource group individually within each cluster.

Thanks :)
