### ISSUE TITLE
Unable to fetch Azure metrics

### ISSUE THREAD

**Issue by Vishnupriya9943** [webdevops/azure-metrics-exporter#82]
I am using  ```Azure metrics exporter``` for fetching azure metrics but I am unable to get my virtual machine metrics while running  below config file.

```./azure-metrics-exporter sample_vm.yml --log.debug```

this is my config file 
``` 
- job_name: azure-metrics-compute
  scrape_interval: 1m
  metrics_path: /metrics
  params:
    name: ["azure_metric_compute"]
    subscription:
    - xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    filter: ["Microsoft.Compute/virtualMachine"]
    metric:
    - CPU Credits Consumed
    - CPU Credits Remaining
    interval: ["PT15M"]
    timespan: ["PT15M"]
    aggregation:
    - average
  static_configs:
  - targets: ["localhost:8080"]
 ```
And i exported my ```client_id``` , ```secret_id```, ```tenant_id```.

sample screenshot 
![azure_metrics_exporter](https://github.com/webdevops/azure-metrics-exporter/assets/101937629/5e48b20f-ad66-49e6-aa70-89422b167c6c)

![Screenshot from 2024-03-19 18-14-56](https://github.com/webdevops/azure-metrics-exporter/assets/101937629/97452705-bb0f-43e2-b7e1-b019f24ee10d)

Kindly help me to resolve this one,
Thanks.
