### ISSUE TITLE
Store Account - Services Metrics

### ISSUE THREAD

**Issue by carlosrodgut** [webdevops/azure-metrics-exporter#9]
## Expected Behavior

We expect to collect the metrics from the Services on the Azure Storage Accounts.

- Blob Service -> **containers**
- File Service -> **shares**
- Queue Service -> **queues**
- Table Services -> **tables**

## Actual Behavior

Using the Supported Metrics in Azure (filtering with "resourceType eq")  we get a empty list as result: `{"value":[]}`

Blobs - https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftstoragestorageaccountsblobservices
Files - https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftstoragestorageaccountsfileservices
Queues - https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftstoragestorageaccountsqueueservices
Tables - https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftstoragestorageaccountstableservices (edited)  

## Steps to Reproduce the Problem

  1. Use `/probe/metrics/list` endpoint
  2. Set _filter_ parameter to `ResourceType eq 'Microsoft.Storage/storageAccounts/blobServices'`
  3. Enable debug mode on Azure SDK
  ( Environment Variable AZURE_GO_SDK_LOG_LEVEL equal to DEBUG )
  4. The response to the HTTP request to any of the aforementioned supported metrics will return `{"value":[]}`.

## Specifications

  - Version: 21.5.4

**Comment by mblaschke** [comment]
could you try `quay.io/webdevops/azure-metrics-exporter:metric-namespace-support`?

with configuration like https://github.com/webdevops/azure-metrics-exporter/tree/metric-namespace-support#storageaccount-metric-namespace-and-dimension-support

**Comment by carlosrodgut** [comment]
Hi @mblaschke ,

Thanks for include the dimension support on the exporter.

We have tested and managed to collect the metrics from the **Queues** on a Storage Account with two additional jobs with the next values:
```
- job_name: azure-metrics-storage-account-queue-capacity
  honor_timestamps: true
  params:
    aggregation:
    - Average
    - Minimum
    - Maximum
    - Total
    filter:
    - resourceType eq 'Microsoft.Storage/storageAccounts'
    interval:
    - PT60M
    metric:
    - QueueCapacity
    - QueueCount
    - QueueMessageCount
    metricNamespace:
    - Microsoft.Storage/storageAccounts/queueServices
    metricTop:
    - "10"
    name:
    - az_storage_account_queue_capacity
    resourceSubPath:
    - queueServices/default
    subscription:
    - SUBSCRIPTION
    timespan:
    - PT60M
  scrape_interval: 5m
  scrape_timeout: 5m
  metrics_path: /probe/metrics/list
  scheme: http
  static_configs:
  - targets:
    - webdevops-ame.monitoring.svc.cluster.local:8080
```

```
- job_name: azure-metrics-storage-account-queue-transactions
  honor_timestamps: true
  params:
    aggregation:
    - Average
    - Minimum
    - Maximum
    - Total
    filter:
    - resourceType eq 'Microsoft.Storage/storageAccounts'
    interval:
    - PT5M
    metric:
    - Availability
    - Egress
    - Ingress
    - SuccessE2ELatency
    - SuccessServerLatency
    - Transactions
    metricFilter:
    - ApiName eq '*'
    metricNamespace:
    - Microsoft.Storage/storageAccounts/queueServices
    metricTop:
    - "10"
    name:
    - az_storage_account_queue_transactions
    resourceSubPath:
    - queueServices/default
    subscription:
    - SUBSCRIPTION
    timespan:
    - PT5M
  scrape_interval: 5m
  scrape_timeout: 5m
  metrics_path: /probe/metrics/list
  scheme: http
  static_configs:
  - targets:
    - webdevops-ame.monitoring.svc.cluster.local:8080
```

**Comment by carlosrodgut** [comment]
Hi @mblaschke,

In order to collect most of the available metrics (Storage Accounts, Blobs and Queues), we extended the configuration and defined some additional Jobs.

In the Portal all the metrics that contain `dimension` show the option `Apply Splitting` and `Supports filtering and grouping`.

### Storage Account - UsedCapacity
The only possible value for the `interval` is 60 minutes (PT60M).
Namespace: No
Dimension: No
```
- job_name: azure-metrics-storage-account-capacity
  honor_timestamps: true
  params:
    aggregation:
    - Average
    - Minimum
    - Maximum
    - Total
    filter:
    - resourceType eq 'Microsoft.Storage/storageAccounts'
    interval:
    - PT60M
    metric:
    - UsedCapacity
    metricTop:
    - "10"
    name:
    - az_storage_account
    subscription:
    - SUBSCRIPTION
    timespan:
    - PT60M
  scrape_interval: 5m
  scrape_timeout: 5m
  metrics_path: /probe/metrics/list
  scheme: http
  static_configs:
  - targets:
    - webdevops-ame.monitoring.svc.cluster.local:8080
```

### Storage Account - Transaction
The metrics grouped under `Transaction` are common to other Services ( Queues and Blobs ).
Those accepts many combination for `interval` and `timespan`.
Namespace: No
Dimension: No
```
- job_name: azure-metrics-storage-account-transactions
  honor_timestamps: true
  params:
    aggregation:
    - Average
    - Minimum
    - Maximum
    - Total
    filter:
    - resourceType eq 'Microsoft.Storage/storageAccounts'
    interval:
    - PT5M
    metric:
    - Availability
    - Egress
    - Ingress
    - SuccessE2ELatency
    - SuccessServerLatency
    - Transactions
    metricTop:
    - "10"
    name:
    - az_storage_account
    subscription:
    - SUBSCRIPTION
    timespan:
    - PT5M
  scrape_interval: 5m
  scrape_timeout: 5m
  metrics_path: /probe/metrics/list
  scheme: http
  static_configs:
  - targets:
    - webdevops-ame.monitoring.svc.cluster.local:8080
```

### Storage Account - Blob - Capacity (With dimension)
The required `Namespace` and the `Metric Filter` are present for the _Blob service_.
Only some of the metrics grouped under `Capacity` have dimensions.
Namespace: **Yes**
Dimension: **Yes**
```
- job_name: azure-metrics-storage-account-capacity-blob
  honor_timestamps: true
  params:
    aggregation:
    - Average
    - Minimum
    - Maximum
    - Total
    filter:
    - resourceType eq 'Microsoft.Storage/storageAccounts'
    interval:
    - PT60M
    metric:
    - BlobCapacity
    - BlobCount
    metricFilter:
    - BlobType eq '*'
    metricNamespace:
    - Microsoft.Storage/storageAccounts/blobServices
    metricTop:
    - "10"
    name:
    - az_storage_account
    resourceSubPath:
    - blobServices/default
    subscription:
    - SUBSCRIPTION
    timespan:
    - PT60M
  scrape_interval: 5m
  scrape_timeout: 5m
  metrics_path: /probe/metrics/list
  scheme: http
  static_configs:
  - targets:
    - webdevops-ame.monitoring.svc.cluster.local:8080
```

### Storage Account - Blob - Capacity (No dimension)
The required Namespace for the Blob service is defined but the metrics don't have dimension, hence we don't add the `Metric Filter`.
Only some of the metrics grouped under `Capacity` have dimensions.
Namespace: **Yes**
Dimension: No
```
- job_name: azure-metrics-storage-account-capacity-blob-nodimensions
  honor_timestamps: true
  params:
    aggregation:
    - Average
    - Minimum
    - Maximum
    - Total
    filter:
    - resourceType eq 'Microsoft.Storage/storageAccounts'
    interval:
    - PT60M
    metric:
    - ContainerCount
    - IndexCapacity
    metricNamespace:
    - Microsoft.Storage/storageAccounts/blobServices
    metricTop:
    - "10"
    name:
    - az_storage_account
    resourceSubPath:
    - blobServices/default
    subscription:
    - SUBSCRIPTION
    timespan:
    - PT60M
  scrape_interval: 5m
  scrape_timeout: 5m
  metrics_path: /probe/metrics/list
  scheme: http
  static_configs:
  - targets:
    - webdevops-ame.monitoring.svc.cluster.local:8080
```


### Storage Account - Blob - Transaction
The metrics grouped under `Transaction` are common to other entities ( Queues and Blobs ).
Those accepts many combination for `interval` and `timespan`.
Namespace: **Yes**
Dimension: **Yes**
```
- job_name: azure-metrics-storage-account-transactions-blob
  honor_timestamps: true
  params:
    aggregation:
    - Average
    - Minimum
    - Maximum
    - Total
    filter:
    - resourceType eq 'Microsoft.Storage/storageAccounts'
    interval:
    - PT5M
    metric:
    - Availability
    - Egress
    - Ingress
    - SuccessE2ELatency
    - SuccessServerLatency
    - Transactions
    metricFilter:
    - ApiName eq '*'
    metricNamespace:
    - Microsoft.Storage/storageAccounts/blobServices
    metricTop:
    - "10"
    name:
    - az_storage_account
    resourceSubPath:
    - blobServices/default
    subscription:
    - SUBSCRIPTION
    timespan:
    - PT5M
  scrape_interval: 5m
  scrape_timeout: 5m
  metrics_path: /probe/metrics/list
  scheme: http
  static_configs:
  - targets:
    - webdevops-ame.monitoring.svc.cluster.local:8080
```

### Storage Account - Queu - Capacity
Namespace: **Yes**
Dimension: No
```
- job_name: azure-metrics-storage-account-capacity-queue
  honor_timestamps: true
  params:
    aggregation:
    - Average
    - Minimum
    - Maximum
    - Total
    filter:
    - resourceType eq 'Microsoft.Storage/storageAccounts'
    interval:
    - PT60M
    metric:
    - QueueCapacity
    - QueueCount
    - QueueMessageCount
    metricNamespace:
    - Microsoft.Storage/storageAccounts/queueServices
    metricTop:
    - "10"
    name:
    - az_storage_account
    resourceSubPath:
    - queueServices/default
    subscription:
    - SUBSCRIPTION
    timespan:
    - PT60M
  scrape_interval: 5m
  scrape_timeout: 5m
  metrics_path: /probe/metrics/list
  scheme: http
  static_configs:
  - targets:
    - webdevops-ame.monitoring.svc.cluster.local:8080
```

### Storage Account - Queue - Transaction
Namespace: **Yes**
Dimension: **Yes**
```
- job_name: azure-metrics-storage-account-transactions-queue
  honor_timestamps: true
  params:
    aggregation:
    - Average
    - Minimum
    - Maximum
    - Total
    filter:
    - resourceType eq 'Microsoft.Storage/storageAccounts'
    interval:
    - PT5M
    metric:
    - Availability
    - Egress
    - Ingress
    - SuccessE2ELatency
    - SuccessServerLatency
    - Transactions
    metricFilter:
    - ApiName eq '*'
    metricNamespace:
    - Microsoft.Storage/storageAccounts/queueServices
    metricTop:
    - "10"
    name:
    - az_storage_account
    resourceSubPath:
    - queueServices/default
    subscription:
    - SUBSCRIPTION
    timespan:
    - PT5M
  scrape_interval: 5m
  scrape_timeout: 5m
  metrics_path: /probe/metrics/list
  scheme: http
  static_configs:
  - targets:
    - webdevops-ame.monitoring.svc.cluster.local:8080
```
